sudo: false
# This repository doesn't contain Python code, but it uses Python tooling.
language: python
python:
  - "2.7"
install:
  - pip install sphinx pygments lxml html5lib setuptools --upgrade
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update
script:
  - make html
  - ./linkcheck.sh
notifications:
  email: false
