sudo: false
# This repository doesn't contain Python code, but it uses Python tooling.
language: python
python:
  - "2.7"
install:
  - pip install sphinx pygments lxml
  - git clone https://github.com/tabatkins/bikeshed.git
  - export PATH=$PATH:$PWD/bikeshed/
  - bikeshed update
script:
  - make html
  - ./linkcheck.sh
notifications:
  email: false
